server:
  port: 8101
spring:
  application:
    name: chatbusiness1

rpc:
  opentracing:
    #opentracing配置
    serviceName: motan_demo_service
    address: http://127.0.0.1:9411/api/v2/spans
  common:
    #注册中心配置
    registry:
      regProtocol: zookeeper #注册中心协议
      address: 192.168.0.30:2181 #注册中心地址
      requestTimeout: 1000 #注册中心连接超时时间(毫秒)
      connectTimeout: 3000 #注册中心请求超时时间(毫秒)
    #协议配置
    protocol:
      name: motan #协议名称
      haStrategy: backup #容错策略
      loadbalance: myConsistent #负载均衡策略
      minWorkerThread: 20 #最小工作pool线程数
      maxWorkerThread: 50 #最大工作pool线程数
    #指定需要解析的包名
    annotation:
      package: com.wyt.motan
  business:
    #服务端配置
    server:
      filter: recordReqId
      export:  'motanProtocol:8601' #服务端口
      group: motan_demo_business
      registry: motanRegistry
    #客户端配置
    client:
      filter: myOpentracing
      protocol: motanProtocol
      group: motan_demo_business
      check: false
      requestTimeout: 30000 #请求超时时间(毫秒)
      connectTimeout: 5000 #连接超时时间(毫秒)
      registry: motanRegistry